% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Inlämningsuppgift block 4 -- hypotestest, konfidensintervall},
  pdfauthor={Statistiska Metoder med R},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Inlämningsuppgift block 4 -- hypotestest, konfidensintervall}
\author{Statistiska Metoder med R}
\date{}

\begin{document}
\maketitle

Grupp 10

Namn och personnummer på dem som deltagit aktivt:

Jacob Widaeus 950729

\hfill\break

\hfill\break

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load dependencies}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\textbf{1. En enstaka observation jämförd med en känd population}

Du har tidigare beräknat hur stor andel av befolkningen som har
blodtrycket 80mmHg eller lägre. Förutsättningen för din beräkning är att
variabeln blodtryck är normalfördelad, samt att du känner till
medelvärdet och standardavvikelsen för populationen.

Samma typ av beräkning kan användas för ett hypotestest, en beräkning
som talar om hur ovanlig en observation är, förutsatt att nollhypotesen
är sann. Tänk dig att du mäter blodtryck på en person, resultatet blir
72 mmHg. Frågan som intresserar dig är: Hör den här personen till
gruppen vanliga friska, eller hör hon till en grupp sjuka som i
genomsnitt har lägre blodtyck än friska?

\textbf{Kommenterat exempel}

Nollhypotes: Personen hör till populationen med fördelningen blodtryck
\textasciitilde N(90, 10)

Alternativhypotes: Personen hör till en population med lägre blodtryck
än N(90, 10)

\textbf{1.1} Är det ett ensidigt eller tvåsidigt test vi har formulerat?
Val av signifikansnivå: Vi väljer \(α\) = 0.05. Det innebär att vi
förkastar nollhypotesen om p-värdet är lägre än 0.05. Genom att välja
\(α\) = 0.05 har vi accepterat att om vi gör upprepade tester där
nollhypotesen verkligen är sann så kommer vi förkasta nollhypotesen av
misstag i 5\% av testen på lång sikt.

\hfill\break
Svar: Det är ett ensidigt test eftersom alternativhypotesen anger att
personen hör till en population med lägre blodtryck än N(90, 10).\\

\textbf{1.2} Är det ett typ I eller ett typ II fel att förkasta en sann
nollhypotes?

\hfill\break
Svar: Att förkasta en sann nollhypotes är ett typ I fel.\\

Val av statistisk test: z- test

Titta på figuren ''ensidigt test'' nedan. y är andelen av befolkningen
som har ett blodtryck nära x. Arean under hela kurvan är 1. Det betyder
att alla i befolkningen har ett blodtryck, alla möjliga utfall ryms
under kurvan.

Antag att nollhypotesen stämmer, personen du mätt hör till populationen
N(90, 10). Hur vanligt är det att man får resultatet 72 eller lägre av
en slump? Svaret är arean under kurvan till vänster om bt= 72. Den arean
är det samma som z-testets p-värde.

\textbf{1.3} Beräkna blå area i figuren ''Ensidigt test'' med R

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Given information}
\NormalTok{mean }\OtherTok{\textless{}{-}} \DecValTok{90}
\NormalTok{sd }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{value }\OtherTok{\textless{}{-}} \DecValTok{72}

\CommentTok{\# Beräkna p värdet, för normalfördelad population}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(value, mean, sd)}
\FunctionTok{print}\NormalTok{(p\_value)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.03593032
\end{verbatim}

\textbf{1.4} Återskapa min figur ''Ensidigt test'' nedan med R

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# Givna parametrar}
\NormalTok{mean }\OtherTok{\textless{}{-}} \DecValTok{90}
\NormalTok{sd }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{value }\OtherTok{\textless{}{-}} \DecValTok{72}

\CommentTok{\# Skapa x värden}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(mean }\SpecialCharTok{{-}} \DecValTok{4}\SpecialCharTok{*}\NormalTok{sd, mean }\SpecialCharTok{+} \DecValTok{4}\SpecialCharTok{*}\NormalTok{sd, }\AttributeTok{length=}\DecValTok{1000}\NormalTok{)}
\CommentTok{\# Beräkna fördelning}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x, mean, sd)}
\CommentTok{\# df}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(x, y)}

\CommentTok{\# Plotta}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(x, y)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_area}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(data, x }\SpecialCharTok{\textless{}=}\NormalTok{ value), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{y =}\NormalTok{ y),}
  \AttributeTok{fill =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ value, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Ensidigt test"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Blodtryck"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densitet"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-2-1.pdf}

\textbf{1.5} Blodtrycket bt72 eller lägre verkar förekomma i mindre del
av befolkningen än 0.05, vår valda signifikansnivå. Ska vi behålla eller
förkasta nollhypotesen?

\hfill\break
Svar: Eftersom blodtrycket på 72 mmHg är lägre än signifikansnivån på
5\%, bör vi förkasta nollhypotesen.\\

\textbf{Tvåsidigt test}

Det är vanligt att man måste formulera en tvåsidig alternativhypotes.
När jag drar ett värde så ska jag fråga mig ''hur vanligt är det att
hitta en person som avviker så här mycket från medlet, uppåt eller
neråt''. Det är lika vanligt att avvika 18 mmHg neråt eller mer som 18
mmHg uppåt eller mer. För att beräkna p-värdet för ett tvåsidigt test
måste du summera de två blåa areorna i figuren ''tvåsidigt test'' nedan.
Använd samma mätning igen, 72 mmHg, med en ny alternativhypotes:
Nollhypotes: Personen hör till populationen med fördelningen blodtryck
\textasciitilde N(90, 10) Alternativhypotes: Personen hör till en
population med högre eller lägre blodtryck än N(90, 10)

\textbf{1.6} Kan nollhypotesen förkastas med α = 0.05 som
signifikansnivå?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Given information}
\NormalTok{mean }\OtherTok{\textless{}{-}} \DecValTok{90}
\NormalTok{sd }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{value }\OtherTok{\textless{}{-}} \DecValTok{72}
\NormalTok{alfa }\OtherTok{\textless{}{-}} \FloatTok{0.05}

\CommentTok{\# Beräkna p värde}
\NormalTok{p\_lower }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(value, mean, sd)}
\NormalTok{p\_upper }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(mean }\SpecialCharTok{+}\NormalTok{ (mean }\SpecialCharTok{{-}}\NormalTok{ value), mean, sd, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Two{-}sided}
\NormalTok{p\_value\_two\_sided }\OtherTok{\textless{}{-}}\NormalTok{ p\_lower }\SpecialCharTok{+}\NormalTok{ p\_upper}

\ControlFlowTok{if}\NormalTok{ (p\_value\_two\_sided }\SpecialCharTok{\textless{}}\NormalTok{ alfa) \{}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Nollhypotesen kan förkastas med"}\NormalTok{, }\FunctionTok{round}\NormalTok{(p\_value\_two\_sided, }\DecValTok{4}\NormalTok{)))}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Nollhypotesen kan inte förkastas med"}\NormalTok{, }\FunctionTok{round}\NormalTok{(p\_value\_two\_sided, }\DecValTok{4}\NormalTok{)))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Nollhypotesen kan inte förkastas med 0.0719"
\end{verbatim}

\textbf{Uttrycka skillnader med variation}

Att göra ett experiment handlar ofta om att mäta en skillnad. Blev det
skillnad i blodtryck mellan kontrollgruppen och gruppen som
medicinerats? Ja, alltid blir det någon skillnad mellan två stickprov,
även om medicineringen inte påverkar blodtrycket som du hade hoppats.
Det blir skillnad av en slump. 3 mmHg blev det kanske. Är det mycket
eller lite? Är 10 kg stor skillnad? Kanske för gäddor, kanske inte för
människor. För att besvara frågan måste vi byta ut enheten mmHg, kg, cm
och istället uttrycka skillnaden med variation som enhet. Övningen som
följer ska illustrera detta.

Undersök formeln för z-testet. \[
z = (X-\mu)/σ
\] X är din uppmätta variabel

\(µ\) är medelvärdet för populationen som X hör till enligt
nollhypotesen

\(σ\) är populationens standardavvikelse

Många variabler X kan vara normalfördelade med olika medel och
standardavikelser. Siffrorna blir olika beroende på vilken enhet man
använder.

Titta på variablerna X1 och X2 och deras fördelningar, beskriver de
samma fenomen i naturen? \[
X1 ~ N(\mu = 25 , \sigma = 2.5)
\] \[
X2 ~ N(\mu = 10, \sigma = 1)
\] Javisst, det är längden på en sorts fiskar, X1 är längden angivet i
cm, X2 är längden angivet i tum.

z är en speciell variabel med fördelningen z \textasciitilde N(0, 1),
med andra ord, z är normalfördelad med medelvärdet 0 och
standardavvikelsen 1. För att rita upp z \textasciitilde N(0,1) i R kan
du använda

curve(dnorm(x, 0, 1), from= -4, to=4)

För att transformera en variabel till z behöver du genomföra stegen A
och B nedan:

A. subtrahera µ från varje X - då blir medelvärdet noll

exempel: X = 80 mmHg; X \textasciitilde N(90, 10)

80 mmHg -- 90 mmHg = - 10 mmHg

bt\textless- seq(-50, 120, 1)

y = dnorm(bt, 90, 10)

plot(bt, y, type=``l'', xlim=c(-50, 120), main=``transformera så µ blir
noll'')

lines(bt -90, y, xlim=c(-50, 120), col=``blue'')

B. Dividera varje X med standardavvikelsen -- då blir skalan på x-axeln
standardavvikese.

Fortsättning på samma exempel: -10 mmHg / 10mmHg = -1

\textbf{1.7} Rita en graf som illustrerar transformeringen av x-axelns
skala från mmHg till standardavvikelse

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Skapa en sekvens för blodtrycksvärden}
\NormalTok{bt }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{50}\NormalTok{, }\DecValTok{120}\NormalTok{, }\DecValTok{1}\NormalTok{)}

\CommentTok{\# Beräkna densitetsfunktion för normalfördelning (N(90, 10))}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(bt, }\AttributeTok{mean =} \DecValTok{90}\NormalTok{, }\AttributeTok{sd =} \DecValTok{10}\NormalTok{)}

\CommentTok{\# data.frame}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{bt =}\NormalTok{ bt,}
  \AttributeTok{y =}\NormalTok{ y,}
  \AttributeTok{original =}\NormalTok{ bt,}
  \AttributeTok{subtracted\_mean =}\NormalTok{ bt }\SpecialCharTok{{-}} \DecValTok{90}\NormalTok{,}
  \AttributeTok{standardized =}\NormalTok{ (bt }\SpecialCharTok{{-}} \DecValTok{90}\NormalTok{) }\SpecialCharTok{/} \DecValTok{10}
\NormalTok{)}

\CommentTok{\# Data manipulation för grafen}
\NormalTok{data\_long }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =} \FunctionTok{c}\NormalTok{(original, subtracted\_mean, standardized),}
               \AttributeTok{names\_to =} \StringTok{"transformation"}\NormalTok{,}
               \AttributeTok{values\_to =} \StringTok{"value"}\NormalTok{)}

\CommentTok{\# Plotta}
\FunctionTok{ggplot}\NormalTok{(data\_long, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ value, }\AttributeTok{y =}\NormalTok{ y, }\AttributeTok{color =}\NormalTok{ transformation)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"blue"}\NormalTok{, }\StringTok{"red"}\NormalTok{),}
                     \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Original (mmHg)"}\NormalTok{,}
                                \StringTok{"Subtraherat medelvärdet"}\NormalTok{,}
                                \StringTok{"Skala: standardavvikelse"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Transformering från mmHg till standardavvikelse"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Blodtryck (mmHg)"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Densitet"}\NormalTok{,}
       \AttributeTok{color =} \StringTok{"Transformation"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlim}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{50}\NormalTok{, }\DecValTok{150}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning: Removed 90 rows containing missing values or values outside the scale range
(`geom_line()`).
\end{verbatim}

\includegraphics{block4_files/figure-pdf/warning- false-1.pdf}

\textbf{2. Ett stickprov jämförs med en känd population}

Du har i inlämningsuppgift 3 dragit upprepade stickprov ur populationer
med olika underliggande fördelningar. Du har även läst om central limit
theorem att samplingsfördelningen går mot normalfördelning om
stickprovet är stort nog.

Du vill testa om ett stickprov är draget ur en population med känt
medelvärde och standardavvikelse. Rätt metod är z-test, men formeln ser
något annorlunda ut än i 1. \[
z = \frac{\bar{X} - \mu}{\frac{sigma}{\sqrt{n}}}
\]

\(\bar{X}\) är stickprovets medelvärde

\(µ\) är populationens medelvärde

\(n\) är stickprovets storlek

\({\sqrt{n}}\) är kvadratroten ur stickprovets storlek

\textbf{2.1} Varför dividerar man populationens standardavvikelse med
kvadratroten ur stickprovets storlek. Du behöver inte härleda
matematiken exakt, men anknyt gärna till resultaten i inlämningsuppgift
3 i ditt svar.

Kvalitetskontrollavdelningen på en fabrik testar regelbundet en produkt.
Medelvikten är 31.2 g med standardavvikelsen 0.4 g. En morgon vägs ett
slumpmässigt stickprov av produkten, 16 exemplar, och stickprovets
medelvikt uppmäts till 31.38 g.

Är produkten tyngre än normalt denna morgon?

\hfill\break
Svar: Anledningen till att man dividerar populationens standardavvikelse
(\(\sigma\)) med kvadratroten av stickprovets storlek (√n) är för att
hantera osäkerheten i uppskattningen av medelvärdet från stickprovet.
Enligt central limit theorem blir samplingsfördelningen av stickprovets
medelvärde normalfördelad när stickprovet är stort nog, och dess
spridning minskar när stickprovet blir större.\\

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Parametrar}
\NormalTok{mu }\OtherTok{\textless{}{-}} \FloatTok{31.2}          \CommentTok{\# Populationens medelvärde}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FloatTok{0.4}        \CommentTok{\# Populationens standardavvikelse}
\NormalTok{x\_bar }\OtherTok{\textless{}{-}} \FloatTok{31.38}      \CommentTok{\# Stickprovets medelvärde}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{16}             \CommentTok{\# Stickprovets storlek}

\CommentTok{\# Beräkna z{-}värdet}
\NormalTok{z\_value }\OtherTok{\textless{}{-}}\NormalTok{ (x\_bar }\SpecialCharTok{{-}}\NormalTok{ mu) }\SpecialCharTok{/}\NormalTok{ (sigma }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}

\CommentTok{\# Beräkna p{-}värdet (ensidigt test, höger{-}svans)}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{(z\_value)}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Z{-}värde:"}\NormalTok{, z\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Z-värde: 1.8"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"P{-}värde:"}\NormalTok{, p\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "P-värde: 0.035930319112926"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (p\_value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{) \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Produkten är signifikant tyngre än normalt."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Produkten är signifikant tyngre än normalt."
\end{verbatim}

\textbf{2.2} Ange nollhypotes och mothypotes

\hfill\break
Svar: Nollhypotes (\(H₀\)): Det finns ingen skillnad i medelvikt, dvs.
produkternas medelvikt är fortfarande 31.2 g. Stickprovet kommer från
samma population. Mothypotes (\(H₁\)): Produkten är tyngre än normalt
denna morgon.\\

\textbf{2.3} välj signifikansnivå

\hfill\break
Svar: En vanlig signifikansnivå är 5\%, vilket innebär att vi förkastar
nollhypotesen om sannolikheten att observera ett stickprov med den
uppmätta medelvikten, eller mer extremt, är mindre än 5\%.\\

\textbf{2.4} Beräkna z-test i R.

Du kan transformera X till z med formeln
\(z = \frac{\bar{X} - \mu}{\frac{sigma}{\sqrt{n}}}\) och sedan slå upp p
värdet med pnorm(). Så måste du göra om du bara har en z-tabell att
tillgå för att komma åt p-värdet.

Det går även utmärkt att låta R göra transformeringen genom att fylla i
värdet i g i pnorm() tillsammans med medel och standardavvikelse i gram.

Ange om nollhypotesen förkastas eller behålls.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Parametrar}
\NormalTok{mu }\OtherTok{\textless{}{-}} \FloatTok{31.2}          \CommentTok{\# Populationens medelvärde}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FloatTok{0.4}        \CommentTok{\# Populationens standardavvikelse}
\NormalTok{x\_bar }\OtherTok{\textless{}{-}} \FloatTok{31.38}      \CommentTok{\# Stickprovets medelvärde}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{16}             \CommentTok{\# Stickprovets storlek}

\CommentTok{\# Beräkna z{-}värdet}
\NormalTok{z\_value }\OtherTok{\textless{}{-}}\NormalTok{ (x\_bar }\SpecialCharTok{{-}}\NormalTok{ mu) }\SpecialCharTok{/}\NormalTok{ (sigma }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}

\CommentTok{\# Beräkna p{-}värdet (ensidigt test, höger{-}svans)}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{(z\_value)}

\CommentTok{\# Skriv ut resultaten}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Z{-}värde:"}\NormalTok{, z\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Z-värde: 1.8"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"P{-}värde:"}\NormalTok{, p\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "P-värde: 0.035930319112926"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Kontrollera om vi kan förkasta nollhypotesen}
\ControlFlowTok{if}\NormalTok{ (p\_value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{) \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Nollhypotesen förkastas. Produkten är signifikant tyngre än normalt."}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Nollhypotesen behålls. Det finns ingen signifikant skillnad i produktens vikt."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Nollhypotesen förkastas. Produkten är signifikant tyngre än normalt."
\end{verbatim}

\textbf{2.5} Rita en graf som visar stickprovens förväntade fördelning
och arean som motsvarar p-värdet. Välj själv om du vill rita grafen med
X (otransformerade värden i gram) eller med z (transformerade värden,
standardavvikelsen som enhet) som x-axel.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Skapa en data frame för normalfördelningen}
\NormalTok{bt\_values }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FloatTok{30.8}\NormalTok{, }\FloatTok{31.5}\NormalTok{, }\AttributeTok{length.out =} \DecValTok{100}\NormalTok{)}
\NormalTok{densities }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(bt\_values, }\AttributeTok{mean =}\NormalTok{ mu, }\AttributeTok{sd =}\NormalTok{ sigma }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{bt\_values =}\NormalTok{ bt\_values, }\AttributeTok{densities =}\NormalTok{ densities)}

\CommentTok{\# Skapa en data frame för p{-}värdesområdet}
\NormalTok{fill\_values }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(x\_bar, }\FloatTok{31.5}\NormalTok{, }\AttributeTok{length.out =} \DecValTok{100}\NormalTok{)}
\NormalTok{fill\_densities }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(fill\_values, }\AttributeTok{mean =}\NormalTok{ mu, }\AttributeTok{sd =}\NormalTok{ sigma }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}
\NormalTok{fill\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{fill\_values =}\NormalTok{ fill\_values, }\AttributeTok{fill\_densities =}\NormalTok{ fill\_densities)}

\CommentTok{\# Rita grafen}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ bt\_values, }\AttributeTok{y =}\NormalTok{ densities)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Fördelningskurvan}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ x\_bar, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,}
  \AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Stickprovets medelvikt}
  \FunctionTok{geom\_area}\NormalTok{(}\AttributeTok{data =}\NormalTok{ fill\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ fill\_values, }\AttributeTok{y =}\NormalTok{ fill\_densities),}
  \AttributeTok{fill =} \StringTok{"red"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Fyll p{-}värdesområdet}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Fördelning av produktens vikt och p{-}värdet"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Vikt (g)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densitet"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{))  }\CommentTok{\# Centrerar titeln}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-6-1.pdf}

\textbf{2.6} Formulera resultatet från 2.4 utan att använda statistisk
terminologi.

\hfill\break
Svar: Den produkt som vägdes denna morgon verkar vara lite tyngre än vad
som är normalt. Vi har beräknat att sannolikheten för att få ett
resultat som detta, om produkten i genomsnitt faktiskt vägde lika mycket
som den brukar, är låg. Därför kan vi misstänka att vikten på
produkterna denna morgon är högre än vanligt.\\

\textbf{3. Ett stickprov jämförs med en population, standardavvikelsen
är okänd}

Ofta har man inte tillgång till standardavvikelsen för populationen. Då
blir man tvungen att göra en uppskattning av populationens
standardavvikelse \(\sigma\), utifrån stickprovets standardavvikelse som
betecknas SD eller s. Istället för z-test ska man använda t-test

\[
t = \frac{\bar{X} - \mu}{\frac{SD}{\sqrt{n}}}
\]

Det finns en enda z-fördelning, men t-fördelningar finns det många, och
de ser olika ut beroende på antal frihetsgrader. Frihetsgrader är
antalet mätningar, n, minus antalet parametrar som skattas, i vårt fall
är det en parameter, medelvärdet.

\textbf{3.1} Rita följande graf:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}\OtherTok{\textless{}{-}}\FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}
\NormalTok{y}\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x)}
\FunctionTok{plot}\NormalTok{(x,y, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{ )}
\FunctionTok{lines}\NormalTok{(x, }\FunctionTok{dt}\NormalTok{(x, }\DecValTok{10}\NormalTok{), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{ )}
\FunctionTok{lines}\NormalTok{(x, }\FunctionTok{dt}\NormalTok{(x, }\DecValTok{3}\NormalTok{), }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{ )}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{))}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{10}\NormalTok{), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{3}\NormalTok{), }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-7-1.pdf}

Grafen visar en z-fördelning och två t-fördelningar. En med 3
frihetsgrader och en med 10.

Jag har ritat en linje som utesluter 0.025 av arean åt vänster för varje
fördelning.

\textbf{3.2} Viket/vilka av följande påståenden stämmer?

Arean till vänster om abline motsvarar p-värdet för ensidiga test.

\textbf{Det krävs en större avvikelse från µ för att t-testen ska falla
ut som signifikanta än för z-testet.}

\hfill\break
Svar: Detta påstående är rätt. T-fördelningarna (speciellt med färre
frihetsgrader, t.ex. 3) har bredare svansar än z-fördelningen, vilket
innebär att kritiska värden för t-fördelningen ligger längre från
medelvärdet än för z-fördelningen. Det innebär att för att ett t-test
ska bli signifikant, krävs det en större avvikelse från medelvärdet än
för ett z-test, särskilt när antalet frihetsgrader är lågt.\\

\textbf{Hur ditt experiment påverkas av stickprovets storlek}

\textbf{3.3} Kommentera skillnaden mellan z och t. När kan det vara
rimligt att approximera t-testet med ett z-test?

\hfill\break
Svar: Skillnaden mellan z och t: Z-test används när populationens
standardavvikelse är känd och stickprovet är stort. T-test används när
populationens standardavvikelse är okänd och uppskattas från
stickprovet. T-fördelningen liknar normalfördelningen men har bredare
svansar, särskilt vid små stickprov. Approximera t med z: Det kan vara
rimligt att approximera t-testet med ett z-test när stickprovet är
stort, eftersom t-fördelningen närmar sig normalfördelningen ju fler
frihetsgrader man har (dvs. när stickprovsstorleken ökar).\\

En grupp av 32 kvinnor under speciell bevakning av mödravården föder
barn. Medelvikten var 3200 g och standardavvikelsen 800 g. Avviker
medelvikten från den normala medelvikten 3600 g?

\textbf{3.4} Ange nollhypotes och mothypotes

\hfill\break
Svar: Nollhypotes (\(H₀\)): Medelvikten för nyfödda i denna grupp
avviker inte från den normala medelvikten på 3600 g.\\
Mothypotes (\(H₁\)): Medelvikten för nyfödda i denna grupp avviker från
den normala medelvikten.\\

\textbf{3.5} Välj signifikansnivå

\hfill\break
\(\alpha = 0.05\)\\

\textbf{3.6} Beräkna t-test i R och ange p-värde samt om nollhypotesen
förkastas eller behålls

Det finns inbyggda funktioner i R för att räkna ttest. Här skulle jag
vilja att du räknar ut t från formeln
\(t = \frac{\bar{X} - \mu}{\frac{SD}{\sqrt{n}}}\) och slår upp i
t-tabellen pt() hur ovanligt det beräknade t-värdet är. Fundera på om du
ska göra ett ensidigt eller tvåsidigt test. Om du vill kan du beräkna
ett z-test också och jämföra resultatet.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Parametrar}
\NormalTok{x\_bar }\OtherTok{\textless{}{-}} \DecValTok{3200}        \CommentTok{\# Stickprovets medelvärde}
\NormalTok{mu }\OtherTok{\textless{}{-}} \DecValTok{3600}           \CommentTok{\# Populationens medelvärde (enligt H0)}
\NormalTok{sd }\OtherTok{\textless{}{-}} \DecValTok{800}            \CommentTok{\# Stickprovets standardavvikelse}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{32}              \CommentTok{\# Stickprovets storlek}

\CommentTok{\# Beräkna t{-}värdet}
\NormalTok{t\_value }\OtherTok{\textless{}{-}}\NormalTok{ (x\_bar }\SpecialCharTok{{-}}\NormalTok{ mu) }\SpecialCharTok{/}\NormalTok{ (sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}

\CommentTok{\# Tvåsidigt p{-}värde baserat på t{-}värdet}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{pt}\NormalTok{(}\FunctionTok{abs}\NormalTok{(t\_value), }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Skriv ut resultaten}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"t{-}värde:"}\NormalTok{, t\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "t-värde: -2.82842712474619"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"p{-}värde:"}\NormalTok{, p\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "p-värde: 0.00812753887944206"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Beslut om nollhypotesen förkastas}
\ControlFlowTok{if}\NormalTok{ (p\_value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{) \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Nollhypotesen förkastas. Medelvikten avviker signifikant från den normala."}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Nollhypotesen behålls. Det finns ingen signifikant skillnad i medelvikt."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Nollhypotesen förkastas. Medelvikten avviker signifikant från den normala."
\end{verbatim}

\textbf{3.7} Formulera resultatet utan att använda statistisk
terminologi.

\hfill\break
Svar: Barnen i denna grupp verkar i genomsnitt väga mindre än vad som
anses normalt. Skillnaden i vikt är tillräckligt stor för att vi ska
misstänka att det inte är en slump att vikten avviker från den
förväntade genomsnittsvikten.\\

\textbf{4. Jämföra två stickprov gruppvis, populationens
standardavvikelse är okänd}

\textbf{4.1} Skapa en data.frameGruppvis.Vikt med följande data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{vikt =} \FunctionTok{c}\NormalTok{(}\DecValTok{90}\NormalTok{, }\DecValTok{91}\NormalTok{, }\DecValTok{93}\NormalTok{, }\DecValTok{106}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{108}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{105}\NormalTok{,}
  \DecValTok{106}\NormalTok{, }\DecValTok{103}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{96}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{90}\NormalTok{, }\DecValTok{101}\NormalTok{,}
           \DecValTok{90}\NormalTok{, }\DecValTok{91}\NormalTok{, }\DecValTok{85}\NormalTok{, }\DecValTok{99}\NormalTok{, }\DecValTok{93}\NormalTok{, }\DecValTok{104}\NormalTok{, }\DecValTok{89}\NormalTok{, }\DecValTok{103}\NormalTok{,}
           \DecValTok{102}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{103}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{87}\NormalTok{, }\DecValTok{86}\NormalTok{, }\DecValTok{101}\NormalTok{),}
  \AttributeTok{grupp =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{,}
  \StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{,}
            \StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{,}
            \StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}B\textquotesingle{}}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

I den första räkneuppgiften tänker vi oss att grupperna A och B är
slumpmässigt utvalda ur två definierade populationer, kanske utifrån
livsstil eller någon diagnos, som vi vill undersöka med avseende på
vikt. Sammanlagt deltar 32 personer i studien. Har grupperna olika
medelvikt?

\textbf{4.2 Ange nollhypotes och mothypotes}

\hfill\break
Svar: Nollhypotes (\(H₀\)): Det finns ingen skillnad i medelvikter
mellan grupp A och grupp B.\\
Mothypotes (\(H₁\)): Det finns en skillnad i medelvikter mellan grupp A
och grupp B.\\

\textbf{4.3Välj signifikansnivå}

\hfill\break
Svar: \(\alpha = 0.05\)\\

\textbf{4.4 Beräkna t-test, tex så här}

attach(Gruppvis.Vikt)

t.test(vikt \textasciitilde{} grupp, var.equal = TRUE) \#vikt
\textasciitilde grupp ska läsas: vikt förklarat av faktorn grupp

Tolka resultattabellen. Ange p-värde, samt om nollhypotesen förkastas
eller behålls.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(vikt }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grupp, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{var.equal =} \ConstantTok{TRUE}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Nollhypotesen förkastas.}
\StringTok{  Medelvikten avviker signifikant från den normala. p{-}värde:"}\NormalTok{,}
  \FunctionTok{round}\NormalTok{(result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{4}\NormalTok{))}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Nollhypotesen behålls.}
\StringTok{  Det finns ingen signifikant skillnad i medelvikt. p{-}värde:"}\NormalTok{,}
  \FunctionTok{round}\NormalTok{(result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{4}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Nollhypotesen behålls.
  Det finns ingen signifikant skillnad i medelvikt. p-värde: 0.1221
\end{verbatim}

\textbf{4.5 Formulera resultatet utan att använda statistisk
terminologi}

\hfill\break
Svar: Efter att ha analyserat vikten hos personer i två olika grupper
visar vår undersökning att även om det finns en observerad skillnad i
genomsnittsvikt mellan grupperna, är denna skillnad inte statistiskt
signifikant. Med ett p-värde på 0.1221 kan vi inte säkert säga att en
grupp väger mer än den andra utifrån de data som samlats in. Detta
innebär att eventuella skillnader i vikt som observerats potentiellt kan
bero på slumpmässiga variationer.\\

\textbf{Jämföra två stickprov där mätningarna hör ihop parvis,
populationens standardavvikelse är okänd}

En kraftfullare experimentell design när man arbetar med människor, där
den individuella variationen kan vara mycket stor, är att göra upprepade
mätningar på samma individ. Tänk dig att mätningen A är gjord före en
tre veckors kontrollerad diet, och mätningen B är gjord efter. Nu tänker
vi oss alltså att data från 4.1 avser mätningar på bara 16 personer.

Nollhypotes:

Det är krångligt att få till en stram formulering av nollhypotesen utan
att skriva en formel.

Nollhypotesen för ett gruppvis test lyder: ''Stickproven \(\bar{X}_A\)
och \(\bar{X}_B\) är dragna ur samma population'' Det kan illustreras
med formeln \(µA = µB\). Lägg märke till att det inte är samma sak som
\(\bar{X}_A =\bar{X}_B\). Även om stickproven är dragna ur samma
population så tror vi inte att de ska ge exakt samma medelvärde. Det är
den underliggande populationen som vi tror har samma medelvärde hela
tiden.

I ett parvis test beräknas inte gruppernas medelvärde. Istället mäter
man förändringen för varje individ, \(d\), därefter beräknar man
medelvärdet för alla förändringar, \(\bar{d}\). Med hjälp av t-testet
kan vi ställa \(\bar{d}\) i relation till variationen i mätningarna.
\(δ\) är den underliggande populationens sanna skillnad.

\[
t = \frac{\bar{d} - \delta}{\frac{SD}{\sqrt{n}}}
\]

Oftast är nollhypotesen att \(δ = 0\)

Så här brukar formeln se ut:

\[
t = \frac{\bar{d}}{\frac{SD}{\sqrt{n}}}
\]

n är i vårt exempel 16. Vid parvis test är n inte antalet mätningar,
utan antalet par. Antalet frihetsgrader är n-1, antalet par minus ett.

Den goda strategin att räkna parvis t-test är att skapa en data.frame
som visar att mätningarna hör ihop, enligt mottot en rad ett case, en
kolumn en variabel.

\textbf{4.6 Läs in data från 4.1 formatterat på ett nytt sätt}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Parvis.Vikt\textless{}{-} read.table("clipboard", header=T)}

\NormalTok{Parvis.Vikt }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{A =} \FunctionTok{c}\NormalTok{(}\DecValTok{90}\NormalTok{, }\DecValTok{91}\NormalTok{, }\DecValTok{93}\NormalTok{, }\DecValTok{106}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{108}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{105}\NormalTok{,}
  \DecValTok{106}\NormalTok{, }\DecValTok{103}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{96}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{90}\NormalTok{, }\DecValTok{101}\NormalTok{),}
  \AttributeTok{B =} \FunctionTok{c}\NormalTok{(}\DecValTok{90}\NormalTok{, }\DecValTok{91}\NormalTok{, }\DecValTok{85}\NormalTok{, }\DecValTok{99}\NormalTok{, }\DecValTok{93}\NormalTok{, }\DecValTok{104}\NormalTok{, }\DecValTok{89}\NormalTok{, }\DecValTok{103}\NormalTok{,}
  \DecValTok{102}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{103}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{105}\NormalTok{, }\DecValTok{87}\NormalTok{, }\DecValTok{86}\NormalTok{, }\DecValTok{101}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Det är även möjligt att återanvända din gamla data.frame genom att lägga
till paried=T. Normalt känner man ju till i förväg om data hör ihop
parvis eller ej och jag rekommenderar att ni använder strukturen i
data.frame.

t.test(vikt \textasciitilde{} grupp, paired = T)

\textbf{4.7 Beräkna parvis ttest, kommentera varför resultatet blir
annorlunda än vid gruppvis test}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Förutsatt att data frame \textquotesingle{}Parvis.Vikt\textquotesingle{} redan är skapad}
\NormalTok{t\_result }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(Parvis.Vikt}\SpecialCharTok{$}\NormalTok{A, Parvis.Vikt}\SpecialCharTok{$}\NormalTok{B, }\AttributeTok{paired =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Visa resultaten från det parvisa t{-}testet}
\FunctionTok{print}\NormalTok{(t\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Paired t-test

data:  Parvis.Vikt$A and Parvis.Vikt$B
t = 4.6967, df = 15, p-value = 0.0002866
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 2.048174 5.451826
sample estimates:
mean difference 
           3.75 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (t\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Nollhypotesen förkastas.}
\StringTok{  Medelvikten avviker signifikant från den normala. p{-}värde:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(t\_result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{4}\NormalTok{))}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Nollhypotesen behålls.}
\StringTok{  Det finns ingen signifikant skillnad i medelvikt. p{-}värde:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(t\_result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{4}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Nollhypotesen förkastas.
  Medelvikten avviker signifikant från den normala. p-värde: 3e-04
\end{verbatim}

\hfill\break
Svar: Resultaten från ett parvis t-test och ett oberoende t-test kan
skilja sig åt eftersom de hanterar datastrukturer olika. Ett parvis
t-test tar hänsyn till beroenden mellan par av observationer, vilket
minskar effekterna av individuell variation och kan öka den statistiska
kraften. Däremot behandlar ett oberoende t-test observationerna som om
de kommer från helt separata grupper, vilket kan leda till större
inverkan av individuella skillnader på resultaten. Således kan ett
parvis t-test avslöja signifikanta skillnader där ett oberoende t-test
inte gör det, vilket speglar de olika antagandena och metodernas
känslighet.\\

\textbf{5. Illustrera typ I och typ II fel}

Koden nedan ritar upp två normalfördelningar. Tänk er att de är
stickprovsfördelningar och att man kan använda z-fördelningen därför att
stickprovets storlek är stort. Den röda fördelningen, µ1, gäller om
nollhypotesen är sann. Den blåa fördelningen, µ2, gäller om
alternativhypotesen är sann. I den röda fördelningen har jag ritat in
arean 0.025.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}\OtherTok{=}\FunctionTok{seq}\NormalTok{(}\DecValTok{50}\NormalTok{,}\DecValTok{140}\NormalTok{,}\AttributeTok{length=}\DecValTok{200}\NormalTok{)}
\NormalTok{y1}\OtherTok{=}\FunctionTok{dnorm}\NormalTok{(x,}\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x,y1,}\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\NormalTok{y2}\OtherTok{=}\FunctionTok{dnorm}\NormalTok{(x,}\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x,y2,}\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\NormalTok{cord.x1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{((}\FunctionTok{round}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\NormalTok{T))),}
\FunctionTok{seq}\NormalTok{((}\FunctionTok{round}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\NormalTok{T))), }\DecValTok{120}\NormalTok{,}\DecValTok{1}\NormalTok{),}\DecValTok{120}\NormalTok{)}
\NormalTok{cord.y1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FunctionTok{dnorm}\NormalTok{(}
  \FunctionTok{seq}\NormalTok{((}\FunctionTok{round}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\NormalTok{T))), }\DecValTok{120}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{),}\DecValTok{0}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(cord.x1,cord.y1,}\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-13-1.pdf}

Gör ett antal nya grafer:

\textbf{5.1} Rita in en abline som visar gränsen utanför vilken du
skulle förkasta nollhypotesen µ1 = µ2 till förmån för
alternativhypotesen µ1 \textless{} µ2. Signifikansnivån ska vara 0.05

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\DecValTok{50}\NormalTok{, }\DecValTok{140}\NormalTok{, }\AttributeTok{length=}\DecValTok{200}\NormalTok{)}
\NormalTok{y1 }\OtherTok{=} \FunctionTok{dnorm}\NormalTok{(x, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{y2 }\OtherTok{=} \FunctionTok{dnorm}\NormalTok{(x, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(x, y1, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x, y2, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-14-1.pdf}

\textbf{5.2} Rita in två abline som visar gränserna utanför vilka du
skulle förkasta nollhypotesen µ1 = µ2 till förmån för
alternativhypotesen µ1 ≠ µ2. Signifikansnivån ska vara 0.05

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(x, y1, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x, y2, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-15-1.pdf}

\textbf{5.3} Gör en ny 5.2 där du färgar arean som visar risken att
förkasta en sann nollhypotes. Typ I felet.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(x, y1, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x, y2, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}

\CommentTok{\# Färga områden för Typ I fel}
\NormalTok{x\_fill\_left }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FunctionTok{min}\NormalTok{(x), }\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\AttributeTok{length.out=}\DecValTok{100}\NormalTok{)}
\NormalTok{x\_fill\_right }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{max}\NormalTok{(x), }\AttributeTok{length.out=}\DecValTok{100}\NormalTok{)}
\NormalTok{y\_fill\_left }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x\_fill\_left, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{y\_fill\_right }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x\_fill\_right, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(x\_fill\_left, }\FunctionTok{rev}\NormalTok{(x\_fill\_left)),}
\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{length}\NormalTok{(x\_fill\_left)), }\FunctionTok{rev}\NormalTok{(y\_fill\_left)), }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(x\_fill\_right, }\FunctionTok{rev}\NormalTok{(x\_fill\_right)),}
\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{length}\NormalTok{(x\_fill\_right)), }\FunctionTok{rev}\NormalTok{(y\_fill\_right)), }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-16-1.pdf}

\textbf{5.4} Gör en ny 5.2. Vi tänker oss att alternativhypotesen, µ2,
är sann. Färga en area som visar risken att behålla en falsk
nollhypotes. Typ II felet, kallas även β. Beräkna och ange β.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(x, y1, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x, y2, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}

\CommentTok{\# Färga områden för Typ II fel (β)}
\NormalTok{x\_fill\_beta }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\AttributeTok{length.out=}\DecValTok{100}\NormalTok{)}
\NormalTok{y\_fill\_beta }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x\_fill\_beta, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(x\_fill\_beta, }\FunctionTok{rev}\NormalTok{(x\_fill\_beta)),}
\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{length}\NormalTok{(x\_fill\_beta)), }\FunctionTok{rev}\NormalTok{(y\_fill\_beta)), }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-17-1.pdf}

\textbf{5.5} Gör en ny 5.4 där du även färgar arean som visar
sannolikheten att förkasta en falsk nollhypotes. Tips: Det ska bli 1 --
β. Detta kallas även statistisk kraft, statistical power.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(x, y1, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(x, y2, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)), }\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{, }\AttributeTok{border=}\ConstantTok{NA}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{max}\NormalTok{(x)), }\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{, }\AttributeTok{border=}\ConstantTok{NA}\NormalTok{)}

\NormalTok{x\_fill\_power\_left }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FunctionTok{min}\NormalTok{(x), }\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\AttributeTok{length.out=}\DecValTok{100}\NormalTok{)}
\NormalTok{x\_fill\_power\_right }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{max}\NormalTok{(x), }\AttributeTok{length.out=}\DecValTok{100}\NormalTok{)}
\NormalTok{y\_fill\_power\_left }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x\_fill\_power\_left, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{y\_fill\_power\_right }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(x\_fill\_power\_right, }\DecValTok{110}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(x\_fill\_power\_left, }\FunctionTok{rev}\NormalTok{(x\_fill\_power\_left)),}
\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{length}\NormalTok{(x\_fill\_power\_left)), }\FunctionTok{rev}\NormalTok{(y\_fill\_power\_left)), }\AttributeTok{col=}\StringTok{\textquotesingle{}green\textquotesingle{}}\NormalTok{)}
\FunctionTok{polygon}\NormalTok{(}\FunctionTok{c}\NormalTok{(x\_fill\_power\_right, }\FunctionTok{rev}\NormalTok{(x\_fill\_power\_right)),}
\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{length}\NormalTok{(x\_fill\_power\_right)), }\FunctionTok{rev}\NormalTok{(y\_fill\_power\_right)), }\AttributeTok{col=}\StringTok{\textquotesingle{}green\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-18-1.pdf}

\textbf{6. Ickeparametriskt alternativ till t-test}

Data inspirerade av: DIFFERENTIATING DENGUE VIRUS INFECTION FROM SCRUB
TYPHUS IN THAI ADULTS WITH FEVER, GEORGE WATT et al 2003

``{[}\ldots{]} simple criteria to differentiatescrub typhus from dengue
infection are needed {[}\ldots{]},particularly where rapid confirmatory
diagnostic tests are notavailable.''

Vita blodkroppar har räknats hos två patientgrupper som är svåra att
skilja åt: Denguefewer, respektive scrub typhus. Använd en
hypotestest-strategi för att avgöra om antal vita blodceller/ mm3 kan
ligga till grund för differentiell diagnos av scrub typhus och
denguefewer. Man kan \textbf{inte} anta att mätvärdena är
normalfördelade. Välj \(α\) = 0.05.

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
count & diagnosis \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
3000 & dengue \\
3200 & dengue \\
3500 & dengue \\
5068 & dengue \\
5679 & dengue \\
6200 & dengue \\
6300 & dengue \\
7020 & dengue \\
4400 & scrub \\
4500 & scrub \\
5900 & scrub \\
6839 & scrub \\
7561 & scrub \\
9047 & scrub \\
12300 & scrub \\
14000 & scrub \\
\end{longtable}

\textbf{6.1 Läs in data och beräkna ett two sample Wilcoxon test (ISwR
5.4, sid 103)}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Skapa data}
\NormalTok{vbc\_counts }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{3000}\NormalTok{, }\DecValTok{3200}\NormalTok{, }\DecValTok{3500}\NormalTok{, }\DecValTok{5068}\NormalTok{, }\DecValTok{5679}\NormalTok{, }\DecValTok{6200}\NormalTok{, }\DecValTok{6300}\NormalTok{, }\DecValTok{7020}\NormalTok{,}
                \DecValTok{4400}\NormalTok{, }\DecValTok{4500}\NormalTok{, }\DecValTok{5900}\NormalTok{, }\DecValTok{6839}\NormalTok{, }\DecValTok{7561}\NormalTok{, }\DecValTok{9047}\NormalTok{, }\DecValTok{12300}\NormalTok{, }\DecValTok{14000}\NormalTok{)}
\NormalTok{diagnosis }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"dengue"}\NormalTok{, }\DecValTok{8}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"scrub"}\NormalTok{, }\DecValTok{8}\NormalTok{))}

\CommentTok{\# Läs in data som en data frame}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{count =}\NormalTok{ vbc\_counts, }\AttributeTok{diagnosis =}\NormalTok{ diagnosis)}

\CommentTok{\# Utför Wilcoxon test}
\NormalTok{wilcox\_test }\OtherTok{\textless{}{-}} \FunctionTok{wilcox.test}\NormalTok{(count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ diagnosis, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{exact =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Visa resultatet av testet}
\FunctionTok{print}\NormalTok{(wilcox\_test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Wilcoxon rank sum test with continuity correction

data:  count by diagnosis
W = 14, p-value = 0.06608
alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

\textbf{6.2 Hur formuleras nollhypotes och alternativhypotes i
Wicoxontestet?}

\hfill\break
Nollhypotes (\(H₀\)): Medianen av vita blodkroppar är lika mellan
patienter med dengue och scrub typhus. Det innebär att det inte finns
någon skillnad mellan de två gruppernas medianvärden.\\
Alternativhypotes (\(H₁\)): Medianen av vita blodkroppar skiljer sig
mellan patienter med dengue och scrub typhus.\\

\textbf{6.3 Visar testet att en enkel räkning av vita blodkroppar kan
stå till grund för differentiell diagnos?}

\hfill\break
Eftersom p-värdet är större än signifikansnivån kan vi inte förkasta
nollhypotesen. Detta innebär att det inte finns tillräckliga bevis i de
data som samlats för att hävda att det finns en statistiskt signifikant
skillnad i medianantalet vita blodkroppar mellan de två
sjukdomsgrupperna.\\

\textbf{6.4 Ange nollhypotes och mothypotes för t-testet}

\hfill\break
Nollhypotes (\(H₀\)): Medelvärdet av vita blodkroppar är lika mellan de
två diagnosgrupperna.\\
Alternativhypotes (\(H₁\)): Medelvärdet av vita blodkroppar skiljer sig
mellan de två diagnosgrupperna.\\

\textbf{6.5 Beräkna testet, tolka resultatet, formulera slutsats.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Utför t{-}test}
\NormalTok{t\_test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ diagnosis, }\AttributeTok{data =}\NormalTok{ data)}

\CommentTok{\# Visa resultatet av t{-}testet}
\FunctionTok{print}\NormalTok{(t\_test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Welch Two Sample t-test

data:  count by diagnosis
t = -2.256, df = 9.6671, p-value = 0.04856
alternative hypothesis: true difference in means between group dengue and group scrub is not equal to 0
95 percent confidence interval:
 -6121.34819   -23.65181
sample estimates:
mean in group dengue  mean in group scrub 
            4995.875             8068.375 
\end{verbatim}

P-värdet är mindre än signifikansnivån och således så förkastas
nollhypotesen.

\textbf{6.6 Varför blir det olika resultat i 6.3 och 6.5?}

\hfill\break
Svar: Skillnaderna i resultaten kan bero på att de två testerna hanterar
data på olika sätt. Wilcoxontestet är mindre känsligt för extremvärden
och icke-normal datafördelning, vilket kan leda till olika slutsatser
jämfört med t-testet som antar normalfördelning och kan påverkas mer av
outlier-värden och ojämn fördelning av data. Om data inte är
normalfördelade, kan t-testets antaganden vara brutna, vilket ger
missvisande resultat.\\

\textbf{7. Konfidensintervall som metod för hypotestestning}

I resultattabellerna som t.test skapat finner du även
konfidensintervall. Att beräkna konfidensintervall är mycket användbart.
Både för att illustrera hur bra en skattning av en parameter är och för
resonemang som liknar hypotestest.

I ett parvis t-test undersöker vi om \(δ ≠ 0\).

Vi kan skatta \(δ\) med \(\bar{d}\) och titta efter om intervallet
\(\bar{d}\) ± 95\% CI.

Ni har mött tekniken hur man räknar konfidensintervall för medelvärden i
inlämningsuppgift 3, i beräkning av ett blodtryckintervall som gäller
95\% av befolkningen. Här vill jag poängtera att beräkningen blir lite
olika beroende på om populationens standardavvikelse \(σ\), är känd,
eller om man,måste skatta den utifrån ett stickprovs standardavvikelse,
SD. Var vänlig slå upp formlerna i en bok. När \(σ\) är känd går det att
använda z.

\textbf{7.1} En däckfabrikör mäter 10 däck som körts 50000 miles. I
medel är 0.32 tum av mönstret kvar, med standardavvikelsen 0.09 tum.
Beräkna ett 95\% konfidensintervall kring medlet.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data för däckmönster}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{mean\_x }\OtherTok{\textless{}{-}} \FloatTok{0.32}
\NormalTok{sd\_x }\OtherTok{\textless{}{-}} \FloatTok{0.09}

\CommentTok{\# Beräkna konfidensintervall}
\NormalTok{t\_critical }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{) }\CommentTok{\# 95\% CI, tvåsidigt, n{-}1 frihetsgrader}
\NormalTok{error\_margin }\OtherTok{\textless{}{-}}\NormalTok{ t\_critical }\SpecialCharTok{*}\NormalTok{ (sd\_x }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}

\CommentTok{\# Konfidensintervall}
\NormalTok{ci\_lower }\OtherTok{\textless{}{-}}\NormalTok{ mean\_x }\SpecialCharTok{{-}}\NormalTok{ error\_margin}
\NormalTok{ci\_upper }\OtherTok{\textless{}{-}}\NormalTok{ mean\_x }\SpecialCharTok{+}\NormalTok{ error\_margin}

\CommentTok{\# Skriv ut resultaten}
\FunctionTok{cat}\NormalTok{(}\StringTok{"95\% konfidensintervall för däckmönster är mellan"}\NormalTok{, ci\_lower, }\StringTok{"och"}\NormalTok{, ci\_upper, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
95% konfidensintervall för däckmönster är mellan 0.2556179 och 0.3843821 
\end{verbatim}

\textbf{7.2} Kan fabrikören påstå att 0.30 tum brukar vara kvar efter
50000 miles utifrån mätningen?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{claimed\_value }\OtherTok{\textless{}{-}} \FloatTok{0.30}

\CommentTok{\# Kontrollera om påstått värde ligger inom konfidensintervallet}
\ControlFlowTok{if}\NormalTok{ (claimed\_value }\SpecialCharTok{\textgreater{}=}\NormalTok{ ci\_lower }\SpecialCharTok{\&\&}\NormalTok{ claimed\_value }\SpecialCharTok{\textless{}=}\NormalTok{ ci\_upper) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Fabrikören kan påstå att 0.30 tum brukar vara kvar efter 50000 miles,}
\StringTok{  eftersom detta värde ligger inom 95\% konfidensintervallet ["}\NormalTok{, ci\_lower, }\StringTok{","}\NormalTok{, ci\_upper, }\StringTok{"].}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Fabrikören kan inte påstå att 0.30 tum brukar vara kvar efter 50000 miles,}
\StringTok{  eftersom detta värde inte ligger inom 95\% konfidensintervallet ["}\NormalTok{, ci\_lower, }\StringTok{","}\NormalTok{, ci\_upper, }\StringTok{"].}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Fabrikören kan påstå att 0.30 tum brukar vara kvar efter 50000 miles,
  eftersom detta värde ligger inom 95% konfidensintervallet [ 0.2556179 , 0.3843821 ].
\end{verbatim}

\textbf{7.3} Tio slumpmässigt utvalda individer har ett
medelkolesterolvärde på 5,4 mmol/l och standardavvikelsen 0.5 mmol/l.
Beräkna ett 95\% konfidensintervall för medlet.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data för kolesterol}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{mean\_k }\OtherTok{\textless{}{-}} \FloatTok{5.4}
\NormalTok{sd\_k }\OtherTok{\textless{}{-}} \FloatTok{0.5}

\CommentTok{\# Beräkna konfidensintervall}
\NormalTok{t\_critical }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{) }\CommentTok{\# 95\% CI, tvåsidigt, n{-}1 frihetsgrader}
\NormalTok{error\_margin }\OtherTok{\textless{}{-}}\NormalTok{ t\_critical }\SpecialCharTok{*}\NormalTok{ (sd\_k }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}

\CommentTok{\# Konfidensintervall}
\NormalTok{ci\_lower\_k }\OtherTok{\textless{}{-}}\NormalTok{ mean\_k }\SpecialCharTok{{-}}\NormalTok{ error\_margin}
\NormalTok{ci\_upper\_k }\OtherTok{\textless{}{-}}\NormalTok{ mean\_k }\SpecialCharTok{+}\NormalTok{ error\_margin}

\CommentTok{\# Skriv ut resultaten}
\FunctionTok{cat}\NormalTok{(}\StringTok{"95\% konfidensintervall för medelkolesterolvärde är mellan"}\NormalTok{,}
\NormalTok{ci\_lower\_k, }\StringTok{"och"}\NormalTok{, ci\_upper\_k, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
95% konfidensintervall för medelkolesterolvärde är mellan 5.042322 och 5.757678 
\end{verbatim}

\textbf{8 ANOVA -- ANalysisOfVariance}

I denna övning nöjer vi oss med en enklare användning av ANOVA. Vi
betraktar ANOVA som ett sätt att hantera flera samtidiga t-test.

Nollhypotes: µ1= µ2 = µ3

Alternativhypotes: µ1= µ2 = µ3 gäller ej

Vi ställer upp ett antal stickprov och kontrollerar om någon grupp
avviker från de andra.

\textbf{8.1Läs in datasetet med blodtryck hos tre olika grupper av
försökspersoner och beräkna ANOVA} med funktionen anova(lm(blodtryck
\textasciitilde behandling))

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
blodtryck & behandling \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
77 & kontroll \\
77 & kontroll \\
78 & kontroll \\
80 & kontroll \\
81 & kontroll \\
89 & kontroll \\
90 & kontroll \\
96 & kontroll \\
99 & kontroll \\
107 & kontroll \\
59 & medicinering \\
66 & medicinering \\
70 & medicinering \\
73 & medicinering \\
76 & medicinering \\
77 & medicinering \\
78 & medicinering \\
81 & medicinering \\
81 & medicinering \\
91 & medicinering \\
64 & träning \\
66 & träning \\
69 & träning \\
72 & träning \\
73 & träning \\
74 & träning \\
74 & träning \\
80 & träning \\
84 & träning \\
99 & träning \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Skapa datasetet}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{blodtryck =} \FunctionTok{c}\NormalTok{(}\DecValTok{77}\NormalTok{, }\DecValTok{77}\NormalTok{, }\DecValTok{78}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{81}\NormalTok{, }\DecValTok{89}\NormalTok{, }\DecValTok{90}\NormalTok{, }\DecValTok{96}\NormalTok{, }\DecValTok{99}\NormalTok{, }\DecValTok{107}\NormalTok{,}
  \DecValTok{59}\NormalTok{, }\DecValTok{66}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{73}\NormalTok{, }\DecValTok{76}\NormalTok{, }\DecValTok{77}\NormalTok{, }\DecValTok{78}\NormalTok{, }\DecValTok{81}\NormalTok{, }\DecValTok{81}\NormalTok{, }\DecValTok{91}\NormalTok{,}
  \DecValTok{64}\NormalTok{, }\DecValTok{66}\NormalTok{, }\DecValTok{69}\NormalTok{, }\DecValTok{72}\NormalTok{, }\DecValTok{73}\NormalTok{, }\DecValTok{74}\NormalTok{, }\DecValTok{74}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{84}\NormalTok{, }\DecValTok{99}\NormalTok{),}
  \AttributeTok{behandling =} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"kontroll"}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"medicinering"}\NormalTok{, }\DecValTok{10}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"träning"}\NormalTok{, }\DecValTok{10}\NormalTok{))}
\NormalTok{)}

\CommentTok{\# Utför ANOVA}
\NormalTok{anova\_resultat }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(blodtryck }\SpecialCharTok{\textasciitilde{}}\NormalTok{ behandling, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(anova\_resultat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
            Df Sum Sq Mean Sq F value Pr(>F)  
behandling   2  968.5   484.2   4.948 0.0148 *
Residuals   27 2642.5    97.9                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\textbf{8.2}ANOVA räknar ut ett F värde utifrån hur variationen är
fördelad över matrisen. Sök efter värdetPr(\textgreater F) i tabellen,
sannolikheten att få värdet F eller större under förutsättning att
nollhypotesen stämmer. Om denna sannolikhet är mindre än ditt
\(α\)-värde kan du förkasta nollhypotesen.

\hfill\break
Svar: PR(\textgreater F) = 0.0148\\
Således kan nollhypotesen förkastas.\\

\textbf{8.3Välj ett sätt att visualisera data.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ behandling, }\AttributeTok{y =}\NormalTok{ blodtryck, }\AttributeTok{fill =}\NormalTok{ behandling)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Blodtryck efter behandlingstyp"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Behandlingskategori"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Blodtryck"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{block4_files/figure-pdf/unnamed-chunk-25-1.pdf}



\end{document}
